name: Contracts CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies (contracts)
        working-directory: ./contracts
        run: |
          # если нужны node deps в contracts - добавить
          true

      - name: Run forge tests
        working-directory: ./contracts
        run: forge test