name: Contracts CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$HOME/.foundry/bin:$PATH"
          foundryup

      - name: Install dependencies (contracts)
        working-directory: ./contracts
        run: |
          # если нужны node deps в contracts - добавить
          true

      - name: Run forge tests
        working-directory: ./contracts
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          forge test