name: Frontend CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install

      - name: Lint
        working-directory: ./frontend
        run: pnpm run lint

      - name: Build
        working-directory: ./frontend
        run: pnpm run build
