name: CI

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        working-directory: ./contracts
        run: forge fmt --check

      - name: Run Forge build
        working-directory: ./contracts
        run: forge build --sizes

      - name: Run Forge tests
        working-directory: ./contracts
        run: forge test -vvv